version: "2"

services:
  blockchain-connector:
    image: harbor.kosmos.idcp.inovex.io/ondics/blockchain-connector:0.2.5
    build: 
      context: .
      dockerfile: Dockerfile.blockchain-connector
    container_name: blockchain-connector
    environment:
      USE_TLS: "false"
      #- USE_STANDALONE_NO_MQTT: true
      MQTT_BROKER_FQDN: "mqtt-broker"
      BC_API_PRODDATA: "http://164.90.233.34/storage/prodData"
    volumes:
      - ./BCC_config.json:/tmp/BCC_config.json
    ports:
      - 10005:1880

networks:
  default:
    external:
      name: kosmos-local
