version: "2"

services:
  blockchain-connector:
    image: harbor.kosmos.idcp.inovex.io/ondics/blockchain-connector:0.2.5
    build: 
      context: .
      dockerfile: Dockerfile.blockchain-connector